In [10]:
import pandas as pd
import psycopg2

In [2]:
csv_df = pd.read_csv('data/raw/raw_usage_2025_01.csv')
json_df = pd.read_json('data/raw/sessions.json', lines=True)
excel_df = pd.read_excel('data/raw/partner_roaming.xlsx', engine='openpyxl')

In [7]:
csv_df

,msisdn,session_id,timestamp,download_mb,upload_mb,avg_throughput,latency_ms,duration_ms,region
0,2348646173949,4221002795321170,2025-01-12 08:47:15,3.56,0.24,14.02,28,359279,Nairobi
1,2348440335149,9962494994271386,2025-01-23 01:33:30,1.17,0.67,16.20,49,463062,Accra
2,2348350714746,2475401784382813,2025-01-12 01:25:21,1.40,0.19,7.81,74,590875,Kisumu
3,2348511725983,2964801779836353,2025-01-15 07:35:54,0.93,0.80,23.46,168,233198,Kisumu
4,2348150823919,5095802050002150,2025-01-26 11:06:31,0.22,4.77,16.59,106,398300,Lagos
...,...,...,...,...,...,...,...,...,...
495,2348564359605,2980851440833846,2025-01-04 01:53:45,10.93,0.79,2.98,50,327566,Lagos
496,2348947111246,1852132128892391,2025-01-11 11:21:06,1.43,1.52,3.34,156,176572,Kumasi
497,2348810025229,7148670386852370,2025-01-21 07:26:11,1.01,0.96,9.08,100,188898,Lagos
498,2348160405293,3291655746355471,2025-01-06 07:23:46,4.01,0.39,6.59,24,36282,Accra
499,2348444116393,5678956237512673,2025-01-02 22:52:16,5.78,0.16,20.31,195,599452,Kumasi

In [8]:
csv_df.columns

Index(['msisdn', 'session_id', 'timestamp', 'download_mb', 'upload_mb',
       'avg_throughput', 'latency_ms', 'duration_ms', 'region'],
      dtype='object')

In [13]:
conn = psycopg2.connect(
    dbname="skylink_db",
    user="mubbysani",
    password="nightCrawler",
    host="localhost",
    port="5432"
)

# Create a cursor object
cur = conn.cursor()

# Create table usage
cur.execute('''CREATE TABLE IF NOT EXISTS usage (
    msisdn VARCHAR,
    session_id VARCHAR,
    timestamp TIMESTAMP,
    download_mb FLOAT,
    upload_mb FLOAT,
    avg_throughput FLOAT,
    latency_ms INT,
    duration_ms INT,
    region VARCHAR
);''')
conn.commit()

In [14]:
# Insert data into usage table
for index, row in csv_df.iterrows():
    cur.execute('''INSERT INTO usage (msisdn, session_id, timestamp, download_mb, upload_mb, 
                avg_throughput, latency_ms, duration_ms, region)
                   VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s);''',
                (row['msisdn'], row['session_id'], row['timestamp'], row['download_mb'], row['upload_mb'], row['avg_throughput'], row['latency_ms'], row['duration_ms'], row['region']))
conn.commit()

In [16]:
from sqlalchemy import create_engine

engine = create_engine('postgresql+psycopg2://mubbysani:nightCrawler@localhost:5432/skylink_db')

In [18]:
# csv_df.head(0).to_sql('usage', engine, if_exists='replace', index=False)  # Create table
csv_df.to_sql('usage', engine, if_exists='append', index=False)

500

Empty DataFrame
Columns: [session_id, app_category, timestamp, device_type, network_type]
Index: []

In [5]:
csv_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   msisdn          500 non-null    int64
 1   session_id      500 non-null    int64
 2   timestamp       500 non-null    object
 3   download_mb     500 non-null    float64
 4   upload_mb       500 non-null    float64
 5   avg_throughput  500 non-null    float64
 6   latency_ms      500 non-null    int64
 7   duration_ms     500 non-null    int64
 8   region          500 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 35.3+ KB

In [6]:
csv_df.describe()

,msisdn,session_id,download_mb,upload_mb,avg_throughput,latency_ms,duration_ms
count,5.000000e+02,5.000000e+02,500.00000,500.000000,500.000000,500.000000,500.00000
mean,2.348494e+12,5.577796e+15,5.03288,0.943640,12.810800,104.422000,302823.43800
std,2.795119e+08,2.595301e+15,4.99605,0.913486,7.194617,54.640709,171302.72382
min,2.348000e+12,1.019087e+15,0.01000,0.000000,0.510000,12.000000,291.00000
25%,2.348253e+12,3.347102e+15,1.46000,0.280000,6.547500,56.000000,163071.00000
50%,2.348492e+12,5.911552e+15,3.36000,0.645000,12.680000,107.000000,301141.50000
75%,2.348734e+12,7.665025e+15,7.15750,1.340000,19.530000,149.250000,454212.50000
max,2.348988e+12,9.999108e+15,28.47000,5.810000,24.960000,200.000000,599614.00000

In [7]:
csv_df.describe(include=['object'])

                  timestamp  region
count                   500     500
unique                  500       6
top     2025-01-12 08:47:15  Kumasi
freq                      1     103

In [8]:
my_list = ['Samson', 'Daisy', 'Maphosa', 'Onyinye', 'Oluwaseyi']

In [11]:
my_list.append('Mubarak')

In [12]:
csv_df.columns

Index(['msisdn', 'session_id', 'timestamp', 'download_mb', 'upload_mb',
       'avg_throughput', 'latency_ms', 'duration_ms', 'region'],
      dtype='object')

In [15]:
csv_df.isnull().sum()

msisdn            0
session_id        0
timestamp         0
download_mb       0
upload_mb         0
avg_throughput    0
latency_ms        0
duration_ms       0
region            0
dtype: int64

In [17]:
csv_df.duplicated().sum()

np.int64(0)

In [ ]:
csv_df[csv_df['download_mb'] > 10].to_csv('Downloads more than 10.csv', index=True)

,msisdn,session_id,timestamp,download_mb,upload_mb,avg_throughput,latency_ms,duration_ms,region
5,2348034036106,7949363556387351,2025-01-26 10:24:00,10.09,1.09,4.23,196,480810,Abuja
15,2348371909209,5441093072229094,2025-01-29 17:06:00,16.78,2.03,3.71,13,214432,Kumasi
18,2348151099178,6578337258498141,2025-01-12 15:46:07,10.68,1.96,15.84,62,580738,Nairobi
24,2348854717664,5955261029832934,2025-01-18 10:14:18,10.17,0.26,24.57,156,342347,Kisumu
28,2348708251920,3768853490200017,2025-01-16 21:46:18,14.35,0.07,19.11,132,79089,Accra
...,...,...,...,...,...,...,...,...,...
474,2348081845308,9597880385473597,2025-01-14 02:02:55,12.68,0.03,15.31,123,360801,Nairobi
476,2348505324119,5739063934506865,2025-01-24 03:33:02,15.13,1.25,5.72,110,1411,Kisumu
479,2348747397617,8408882671138226,2025-01-15 14:56:59,13.44,0.67,19.28,141,493268,Kumasi
493,2348331207458,4702522882093044,2025-01-28 02:31:15,22.77,0.83,6.02,145,236246,Nairobi
495,2348564359605,2980851440833846,2025-01-04 01:53:45,10.93,0.79,2.98,50,327566,Lagos

In [8]:
csv_df.value_counts(["msisdn", "session_id"])

msisdn         session_id
2348000186043  6875638997793882    1
2348652540830  8108464305901549    1
2348676785681  5639280942075263    1
2348676641251  7524229405246578    1
2348673921685  9965741496654587    1
                                  ..
2348331207458  4702522882093044    1
2348329769293  8303786520045060    1
2348329175933  5504516934259419    1
2348324683971  3652619639973068    1
2348988203079  3673648271039384    1
Name: count, Length: 500, dtype: int64

In [20]:
# download_mb -> Download MB
csv_df.rename(columns={
    'download_mb': 'Download MB',
    'upload_mb': 'Upload MB'
})

,msisdn,session_id,timestamp,Download MB,Upload MB,avg_throughput,latency_ms,duration_ms,region
0,2348646173949,4221002795321170,2025-01-12 08:47:15,3.56,0.24,14.02,28,359279,Nairobi
1,2348440335149,9962494994271386,2025-01-23 01:33:30,1.17,0.67,16.20,49,463062,Accra
2,2348350714746,2475401784382813,2025-01-12 01:25:21,1.40,0.19,7.81,74,590875,Kisumu
3,2348511725983,2964801779836353,2025-01-15 07:35:54,0.93,0.80,23.46,168,233198,Kisumu
4,2348150823919,5095802050002150,2025-01-26 11:06:31,0.22,4.77,16.59,106,398300,Lagos
...,...,...,...,...,...,...,...,...,...
495,2348564359605,2980851440833846,2025-01-04 01:53:45,10.93,0.79,2.98,50,327566,Lagos
496,2348947111246,1852132128892391,2025-01-11 11:21:06,1.43,1.52,3.34,156,176572,Kumasi
497,2348810025229,7148670386852370,2025-01-21 07:26:11,1.01,0.96,9.08,100,188898,Lagos
498,2348160405293,3291655746355471,2025-01-06 07:23:46,4.01,0.39,6.59,24,36282,Accra
499,2348444116393,5678956237512673,2025-01-02 22:52:16,5.78,0.16,20.31,195,599452,Kumasi

In [ ]:
# 
median_dm = csv_df['download_mb'].median()
print(median_dm)

3.36

In [23]:
csv_df['download_mb'] = csv_df['download_mb'].fillna(median_dm)

In [ ]:
csv_df = pd.read_csv('data/raw/raw_usage_2025_01.csv')
json_df = pd.read_json('data/raw/sessions.json', lines=True)
excel_df = pd.read_excel('data/raw/partner_roaming.xlsx', engine='openpyxl')

In [ ]:
RAW_USAGE_CSV = 'data/raw/raw_usage_2025_01.csv'

In [ ]:
def read_usage_csv() -> pd.DataFrame:
    try:
        df = pd.read_csv(RAW_USAGE_CSV)
        return df
    except FileNotFoundError:
        print(f"[extract] WARNING: CSV file not found")
        return pd.DataFrame()

In [25]:
csv_df.columns

Index(['msisdn', 'session_id', 'timestamp', 'download_mb', 'upload_mb',
       'avg_throughput', 'latency_ms', 'duration_ms', 'region'],
      dtype='object')

In [ ]:
# Standardize columns
csv_df = csv_df.copy()
json_df = json_df.copy()
excel_df = excel_df.copy()

csv_df = csv_df.columns.str.lower().str.strip().str.replace(" ", "_", regex=False)
json_df = json_df.columns.str.lower().str.strip().str.replace(" ", "_", regex=False)
excel_df = excel_df.columns.str.lower().str.strip().str.replace(" ", "_", regex=False)

In [ ]:
csv_df['timestamp'] = pd.to_datetime(csv_df['timestamp'], errors="coerce", utc=True)

In [3]:
# Fill missing values: avg_throughtput
# Drop duplicates on session_id
# Create another column from download_mb and upload_mb (total_usage_mb)

median_tp = csv_df['avg_throughput'].median()
csv_df["avg_throughput"] = csv_df["avg_throughput"].fillna(median_tp)

csv_df = csv_df.drop_duplicates(subset=["session_id"], keep='first')

csv_df = csv_df[csv_df['duration_ms'] >= 0]

csv_df['total_usage_mb'] = csv_df['download_mb'].fillna(0) + csv_df['upload_mb'].fillna(0)

In [4]:
json_df['app_category'] = json_df['app_category'].fillna('unknown')

In [ ]:
def clean_usage(df: pd.DataFrame) -> pd.DataFrame:
    if "avg_throughput" in df.columns:
        median_tp = df['avg_throughput'].median()
        df["avg_throughput"] = df["avg_throughput"].fillna(median_tp)

    if "app_category" in df.columns:
        df['app_category'] = df['app_category'].fillna('unknown')

    if "duration_ms" in df.columns:
        df = df[df['duration_ms'] >= 0]

    if "session_id" in df.columns:
        df = df.drop_duplicates(subset=["session_id"], keep='first')


    if {"download_mb", "upload_mb"}.issubset(df.columns):
        df['total_usage_mb'] = df['download_mb'].fillna(0) + df['upload_mb'].fillna(0)

    return df

In [ ]:
# GroupBy
csv_df["date"] = csv_df["timestamp"].dt.date
agg = (
    csv_df.groupby(["msisdn", "date"])
    .agg(
        total_usage_mb=["total_usage_mb", "sum"],
        sessions=("session_id", "nunique"),
        avg_throughput = ("avg_throughput", "mean"),
        avg_latency_ms = ("latency_ms", "mean") if "latency_ms" in csv_df.columns else ("timestamp", "count")
        ).reset_index()
)

agg["total_usage_mb"]= agg["total_usage_mb"].astype(float)
agg["sessions"]= agg["sessions"].astype(int)

Index(['session_id', 'app_category', 'timestamp', 'device_type',
       'network_type'],
      dtype='object')

In [ ]:
def aggregate_daily(df: pd.DataFrame) -> pd.DataFrame:

    if df.empty or "msisdn" not in df.columns or "timestamp" not in df.columns:
        return pd.DataFrame()

    df["date"] = df["timestamp"].dt.date
    agg = (
        df.groupby(["msisdn", "date"])
        .agg(
            total_usage_mb=["total_usage_mb", "sum"],
            sessions=("session_id", "nunique"),
            avg_throughput = ("avg_throughput", "mean"),
            avg_latency_ms = ("latency_ms", "mean") if "latency_ms" in df.columns else ("timestamp", "count")
            ).reset_index()
    )

    agg["total_usage_mb"]= agg["total_usage_mb"].astype(float)
    agg["sessions"]= agg["sessions"].astype(int)

    return agg

In [6]:
excel_df

            msisdn       country  roaming_data_mb  roaming_cost_usd       date
0    2348181515844           USA           182.95            133.73 2025-01-16
1    2348432819834  South Africa           285.04             56.68 2025-01-24
2    2348013166744            UK           107.75             25.86 2025-01-15
3    2348572637592            UK           411.41             86.27 2025-01-20
4    2348363575447  South Africa           300.09             20.41 2025-01-16
..             ...           ...              ...               ...        ...
195  2348936416748           USA           166.85             90.78 2025-01-27
196  2348689402775           USA           100.47             13.41 2025-01-31
197  2348464884933        France           299.93             17.28 2025-01-28
198  2348813757105        France            47.94            137.74 2025-01-21
199  2348941086638           USA           469.30              6.66 2025-01-14

[200 rows x 5 columns]